version: '3'

services:
  serve:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll
  
  build:
    image: jekyll/jekyll:latest
    command: jekyll build
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll      