# Site settings
title: Daniel McAvinue
description: 'dmcavinue.github.io'
url: 'http://dmcavinue.github.io'

author:
  name: 'Daniel McAvinue'
  email: dan@mcavinue.io
  github_username:  dmcavinue

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
