name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - mains

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v6
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.7.0
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }}
          ssh_private_key: ''
          repository: ''
          branch: 'gh-site'
          jekyll_src: './docs'
          jekyll_cfg: '_config.yml'
          jekyll_baseurl: ''
          ruby_ver: ''
          bundler_ver: '>=0'
          cname: ''
          actor: ''
          pre_build_commands: ''